
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Febrina Wijaya  ## put your name
title: 'COMPUTER ENGINEER'  ## your title
location: Taiwan


## Social Profiles
facebook: http://www.facebook.com/febrinawijaya25  ## your facebook account url
twitter: http://www.twitter.com/FebrinaWong  ## your twitter account url


# Update all the sections by editing the files inside _includes folder.
